# Copyright (C) 2021 - present Juergen Zimmermann, Hochschule Karlsruhe
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# Aufruf:   i.a. bereits eingestellt:   $env:SKAFFOLD_PROFILE = 'dev'
#                                       $env:TAG = '1.0.0'
#           skaffold dev
#           skaffold delete

# https://skaffold.dev/docs/references/yaml

apiVersion: skaffold/v3alpha1
kind: Config
metadata:
  name: computer
# https://skaffold.dev/docs/pipeline-stages/builders
#build:
#  artifacts:
#    - image: gruppe2/computer
#      # https://skaffold.dev/docs/pipeline-stages/builders/buildpacks
#      buildpacks:
#        builder: paketobuildpacks/builder:base
#        dependencies:
#          paths: [src/**, package.json]
#  # https://skaffold.dev/docs/pipeline-stages/taggers
#  tagPolicy:
#    envTemplate:
#      template: "{{.TAG}}"
deploy:
  # https://skaffold.dev/docs/pipeline-stages/deployers/helm
  # Alternativen: Kustomize, kpt, kubectl
  helm:
    releases:
      - name: computer
        chartPath: extras/computer
        valuesFiles: [extras/computer/values.yaml]
        namespace: acme
# https://skaffold.dev/docs/environment/profiles
profiles:
  - name: dev
    activation:
      - env: SKAFFOLD_PROFILE=dev
    deploy:
      helm:
        releases:
          - name: computer
            chartPath: extras/computer
            valuesFiles: [extras/computer/values.yaml, extras/computer/dev.yaml]
            namespace: acme
    # https://skaffold.dev/docs/pipeline-stages/port-forwarding
    portForward:
      - resourceType: service
        resourceName: computer
        port: 3000
