' Copyright (C) 2019 - present Juergen Zimmermann, Hochschule Karlsruhe
'
' This program is free software: you can redistribute it and/or modify
' it under the terms of the GNU General Public License as published by
' the Free Software Foundation, either version 3 of the License, or
' (at your option) any later version.
'
' This program is distributed in the hope that it will be useful,
' but WITHOUT ANY WARRANTY; without even the implied warranty of
' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
' GNU General Public License for more details.
'
' You should have received a copy of the GNU General Public License
' along with this program.  If not, see <https://www.gnu.org/licenses/>.

' Preview durch <Alt>d

@startuml Controller-Klasse

interface Promise<T>

package @nestjs/graphql {
  class "@Resolver" as Resolver
  hide Resolver circle

  class "@UseInterceptors" as UseInterceptors
  hide UseInterceptors circle

  class "@Query" as Query
  hide Query circle

  class "@Args" as Args
  hide Args circle

  Resolver .left[hidden].> Promise
}

package computer {
  package entity {
    class Computer <<entity>>
  }

  package service {
    class ComputerReadService << control >>
  }

  package graphql #DDDDDD {
    class "type ComputerDTO = Omit<Computer, 'aktualisiert' | 'erzeugt'>" as ComputerDTO
    hide ComputerDTO circle

    class ComputerQueryResolver << control >> << @Resolver() >> << @UseInterceptors() >> {
      + @Query() async findById(@Args() id: string): Promise<ComputerDTO>
      + @Query() async find(@Args() titel: string |undefined): Promise<ComputerDTO[]>
    }

    ComputerQueryResolver o-up-> "1" ComputerReadService : service
    ComputerQueryResolver ..> ComputerDTO
    ComputerDTO ..> Computer
    ComputerQueryResolver ..> Resolver

    ComputerQueryResolver ..> Promise

    ComputerDTO .[hidden].> Computer
    Computer .[hidden].> Promise
    ComputerReadService .[hidden].> Promise
    Computer .[hidden].> Resolver
    ComputerReadService .[hidden].> Resolver
  }
}

hide empty members

footer (c) Gruppe 2

@enduml
