' Copyright (C) 2019 - present Juergen Zimmermann, Hochschule Karlsruhe
'
' This program is free software: you can redistribute it and/or modify
' it under the terms of the GNU General Public License as published by
' the Free Software Foundation, either version 3 of the License, or
' (at your option) any later version.
'
' This program is distributed in the hope that it will be useful,
' but WITHOUT ANY WARRANTY; without even the implied warranty of
' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
' GNU General Public License for more details.
'
' You should have received a copy of the GNU General Public License
' along with this program.  If not, see <https://www.gnu.org/licenses/>.

' Preview durch <Alt>d

@startuml Komponenten

left to right direction

actor RESTClient
actor GraphQLClient

node "Nest" {
  [RequestLoggerMiddleware]

  [BuchController]
  [BuchResolver]

  [BuchService]

  [Repository<Buch>]

  [MailService]
}


cloud {
    [TypeORM]
}

cloud {
    [nodemailer]
}

database "DB buch" {
    [Tabelle buch]
    [Tabelle schlagwort]
}

node {
    [Mailserver]
}

RESTClient ~~> [RequestLoggerMiddleware]
GraphQLClient ~~> [RequestLoggerMiddleware]

[RequestLoggerMiddleware] ~~> [BuchController]
[RequestLoggerMiddleware] ~~> [BuchResolver]

[BuchController] ..> [BuchService]
[BuchResolver] ..> [BuchService]
[BuchService] ..> [Repository<Buch>]

[Repository<Buch>] ~~> [TypeORM]
[TypeORM] ~~> [Tabelle buch]
[TypeORM] ~~> [Tabelle schlagwort]

[BuchService] ..> [MailService]
[MailService] ~~> [nodemailer]
[nodemailer] ~~> [Mailserver]

footer (c) Jürgen Zimmermann

@enduml
