// Copyright (C) 2020 - present Juergen Zimmermann, Hochschule Karlsruhe
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

//
// N e t z w e r k   -  V e r b i n d u n g   n o t w e n d i g
//

### Login
// @name login
POST {{authUrl}}/login
Content-Type: application/x-www-form-urlencoded

username=admin&password=p

### Login mit falschem Passwort
// @name login
POST {{authUrl}}/login
Content-Type: application/x-www-form-urlencoded

username=admin&password=FALSCHES_PASSWORT

### Login ohne Benutzerkennung
// @name login
POST {{authUrl}}/login
Content-Type: application/x-www-form-urlencoded

### Rollen zu einem Token ermitteln
GET {{authUrl}}/roles
Authorization: Bearer {{login.response.body.$.token}}
