' Copyright (C) 2019 - present Juergen Zimmermann, Hochschule Karlsruhe
'
' This program is free software: you can redistribute it and/or modify
' it under the terms of the GNU General Public License as published by
' the Free Software Foundation, either version 3 of the License, or
' (at your option) any later version.
'
' This program is distributed in the hope that it will be useful,
' but WITHOUT ANY WARRANTY; without even the implied warranty of
' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
' GNU General Public License for more details.
'
' You should have received a copy of the GNU General Public License
' along with this program.  If not, see <https://www.gnu.org/licenses/>.

' Preview durch <Alt>d

@startuml Anwendungskern

interface Promise<T>

package @nestjs/common {
  class "@Injectable" as Injectable
  hide Injectable circle
}

package typeorm {
  class Repository<T>
}

package @nestjs/typeorm {
  class "@InjectRepository" as InjectRepository
  hide InjectRepository circle
}

package mail {
  class MailService
}

package buch {
  package entity {
    class Buch
  }

  package service #DDDDDD {
    class BuchInvalid
    class TitelExists
    class IsbnExists
    class VersionInvalid
    class VersionOutdated

    class BuchWriteService << control >> <<@Injectable()>> {
      + async create(buch: Buch): Promise<string|BuchInvalid|TitelExists|IsbnExists>
      + async update(id: string, buch: Buch, version: string): Promise<number|BuchInvalid|TitelExists|IsbnExists|VersionInvalid|VersionOutdated>
      + async delete(id: string): Promise<boolean>
    }

    BuchWriteService o--> "1" BuchValidationService: validationService
    BuchWriteService o--> "1" BuchReadService: readService
    BuchWriteService o--> "1" Repository: @InjectRepository repo
    BuchWriteService o--> "1" MailService: mailService

    BuchWriteService .up.> Injectable
    BuchWriteService .up.> InjectRepository

    BuchWriteService .up.> Promise
    BuchWriteService ..> Buch
    BuchWriteService .up.> BuchInvalid
    BuchWriteService .up.> TitelExists
    BuchWriteService .up.> IsbnExists
    BuchWriteService .up.> VersionInvalid
    BuchWriteService .up.> VersionOutdated

    BuchInvalid .up[hidden].> Buch
    Buch .up[hidden].> Promise
    Buch .up[hidden].> Injectable
    Buch .up[hidden].> InjectRepository
    TitelExists .up[hidden].> Buch
    BuchValidationService .[hidden].> Repository
    BuchValidationService .[hidden].> MailService
  }
}

hide empty members

footer (c) Jürgen Zimmermann

@enduml
